# Generated by Django 3.2.10 on 2021-12-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211227_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commandetraitee',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
